
#ifndef MAIN_RES_H
#define MAIN_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define MAIN_RES_FILE "Main.bar"

#define IDI_COPYRIGHT		100


#endif  // MAIN_RES_H
