
#ifndef MAIN_RES_H
#define MAIN_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define MAIN_RES_FILE "Main.bar"

#define IDS_DISP		1
#define IDS_GRAPHICS		2
#define IDS_MAINMENUTITLE		3
#define IDI_COPYRIGHT		100
#define IDI_BMP1		5001
#define IDI_BMP2		5002


#endif  // MAIN_RES_H
