
#ifndef MAIN_RES_H
#define MAIN_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define MAIN_RES_FILE "Main.bar"

#define IDS_M_ADD		1
#define IDS_M_SORT		2
#define IDS_M_DELETE		3
#define IDI_COPYRIGHT		100


#endif  // MAIN_RES_H
