
#ifndef MAIN_RES_H
#define MAIN_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define MAIN_RES_FILE "Main.bar"

#define IDI_COPYRIGHT		100
#define IDI_MOUSE		5000
#define IDI_CAT		5001
#define IDI_BRED		5002
#define IDI_BBLUE		5003
#define IDI_GRASS1		6000
#define IDI_GRASS2		6001
#define IDI_GRASS3		6002


#endif  // MAIN_RES_H
