
#ifndef SLIDESHOW_RES_H
#define SLIDESHOW_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define SLIDESHOW_RES_FILE "SlideShow.bar"

#define IDS_TITLE		1
#define IDI_1		1
#define IDI_COPYRIGHT		100


#endif  // SLIDESHOW_RES_H
