
#ifndef ROCKETMILEAGE_RES_H
#define ROCKETMILEAGE_RES_H

// WARNING: DO NOT MODIFY THIS FILE
// AUTO-GENERATED BY BREW Resource Editor

#define ROCKETMILEAGE_RES_FILE "RocketMileage.bar"

#define IDS_TITLE		1
#define IDI_1		1
#define IDI_2		2
#define IDI_3		3
#define IDI_4		4
#define IDI_5		5
#define IDI_6		6
#define IDI_7		7
#define IDI_8		8
#define IDI_9		9
#define IDI_10		10
#define IDI_11		11
#define IDI_12		12
#define IDI_13		13
#define IDI_14		14
#define IDI_15		15
#define IDI_16		16
#define IDI_17		17
#define IDI_18		18
#define IDI_19		19


#endif  // ROCKETMILEAGE_RES_H
